config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :user_profiles

	resources :messages
  resources :invoices, only: [:new]
  resources :questionnaires, only: [:create]

  resources :charges

  get '/order', to: "invoices#order"

  get "/checkout", to: "static_pages#checkout"

	root "static_pages#home"

	get '/about', to: 'static_pages#about'

	get '/contact', to: 'static_pages#contact'

	get '/faqs', to: 'static_pages#faqs'

	post '/contact', to: 'messages#create'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  def self.stripe_params_mapping(params)
    {
      "first_name": params["shipping_name"],
      "zipcode": params["shipping_address_zip"],
      "address": params["shipping_address_line1"].titleize,
      "city": params["shipping_address_city"],
      "state": params["shipping_address_state"]
    }
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, optional: true

  before_save :set_answer_number


  def set_answer_number
    self.answer_number = question.answers.count + 1
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing_address.rb
class BillingAddress < Address
  def self.stripe_params_mapping(params)
    {
      "first_name": params["billing_name"],
      "zipcode": params["billing_zip"],
      "address": params["billing_address_line1"],
      "city": params["billing_address_city"].titleize,
      "state": params["billing_address_state"]
    }
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  before_save :set_invoice_number

  private

  def set_invoice_number
    self.invoice_number = "#{Time.now.strftime("%Y%M%S")}-#{user.id}-#{Invoice.count + 1}"
  end
end

app/models/message.rb
class Message < ApplicationRecord
	validates :name, presence: true, length: { minimum: 3, maximum: 30}
	validates :email, presence: true, length: { minimum: 3, maximum: 30}
	validates :subject, presence: true, length: { minimum: 3, maximum: 30}
	validates :body, presence: true, length: { minimum: 3, maximum: 256}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire, optional: true
  has_many :answers, dependent: :destroy

  default_scope { order(:question_number) }
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :questions
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :invoices
   has_one :questionnaire
   has_one :address
   has_one :billing_address

   def password_required?
    false
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @user = User.find(session[:user_id])
    @invoice = Invoice.find(session[:invoice_id])
  end

  def create
    # Amount in cents
    @amount = render_amount

    customer = Stripe::Customer.create(
      :email => params[:stripe_email],
      :source  => params[:stripe_token]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => '3toZen Purchase',
      :currency    => 'usd'
    )

  save_stripe_info_to_session
  redirect_to new_charge_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end



  private
  # need to handle user buying multiple items or have dif shipping address/billing addresses

  def save_stripe_info_to_session
    user = User.new(email: params[:stripe_email])
    invoice = user.invoices.new(total: 5000, status: "paid")
    user.build_address(Address.stripe_params_mapping(stripe_params))
    user.build_billing_address(BillingAddress.stripe_params_mapping(stripe_params))

    q = Questionnaire.find(session[:questionnaire_id])
    q.zipcode = params["shipping_address_zip"]
    user.questionnaire = q
    if user.save
      session[:user_id] = user.id
      session[:invoice_id] = invoice.id
    end

    session[:item] = params[:item]
  end

  def stripe_params
    params.permit!
  end

  def render_amount
    if params[:item] == "oneMonth"
      8630
    else
      16060
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
		@message = Message.new
	end

	#def show
	#	@message = Message.find(params[:id])
	#end

	def create
		@message = Message.new(message_params)
		if @message.save
			MessagesMailer.send_email(@message).deliver_now!
			flash[:notice] = "Your message has been sent."
			redirect_to contact_path
		else
			flash[:error] = "Sorry, there was an issue sending your message. Try again please."
			redirect_to contact_path
		end
	end

	private
	
		def message_params
			params.require(:messages).permit(:name, :subject, :email, :body)
		end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  def create
    if (q = Questionnaire.create(answer_params)).valid?
      session[:questionnaire_id] = q.id
      render json: {redirectPath: checkout_path}
    else
      render status: 400
    end
  end

  def answer_params
    params[:answers].delete(:step)
    params.require(:answers).permit!
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
  	@message = Message.new
  end

  def faqs
  end

  def checkout
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/charges/new.html.haml
.container-fluid
  .row
    .col-md-12
      %h1.centered Payment Confirmation
      %hr
  .row.invoice
    .col-md-6
      %h5.centered Shipping Address
      .row
        .col-md-4.offset-md-2
          %p Email Address:
        .col-md-4.offset-md-1
          %p=@user.email

        .col-md-4.offset-md-2
          %p Order #:
        .col-md-4.offset-md-1
          %p=@invoice.invoice_number

        .col-md-4.offset-md-2
          %p Shipping Address:
        .col-md-4.offset-md-1
          %p=@user.address.address

        .col-md-4.offset-md-2
          %p Shipping City:
        .col-md-4.offset-md-1
          %p=@user.address.city

        .col-md-4.offset-md-2
          %p Shipping State:
        .col-md-4.offset-md-1
          %p=@user.address.state

        .col-md-4.offset-md-2
          %p Shipping Address:
        .col-md-4.offset-md-1
          %p United States
      %hr

      %h5.centered Billing Address
      .row
        .col-md-4.offset-md-2
          %p Shipping Address:
        .col-md-4.offset-md-1
          %p=@user.billing_address.address

        .col-md-4.offset-md-2
          %p Shipping City:
        .col-md-4.offset-md-1
          %p=@user.billing_address.city

        .col-md-4.offset-md-2
          %p Shipping State:
        .col-md-4.offset-md-1
          %p=@user.billing_address.state

        .col-md-4.offset-md-2
          %p Shipping Address:
        .col-md-4.offset-md-1
          %p United States

      %hr
      %h5.centered Payment
      .row
        .col-md-4.offset-md-2
          %p Subotal:
        .col-md-4.offset-md-1
          %p= session[:item] == "oneMonth" ? "$79.00" : "$147.00"

      .row
        .col-md-4.offset-md-2
          %p Tax:
        .col-md-4.offset-md-1
          %p= session[:item] == "oneMonth" ? "$7.30" : "$13.60"

      .row
        .col-md-4.offset-md-2
          %p Shipping:
        .col-md-4.offset-md-1
          %p FREE
      %hr
      .row
        .col-md-4.offset-md-2
          %h4 Total:
        .col-md-4.offset-md-1
          %h4= session[:item] == "oneMonth" ? "$86.30" : "$160.60"
      %br
    .col-md-6.centered
      = image_tag "product.jpg", class: "product"

app/views/static_pages/about.html.haml
.about
	.row
		.offset-md-3.col-md-6.centered.about-us
			%h1 About Us - Our Story
			%br
			%p It was only through pure serendipity that I gave up by my career as a biotech chemist 20 years ago and became a cosmetic chemist. Having always had a minimalist approach to skincare, the beauty industry was not something I was consciously aware of. But never was I more grateful that I became one than that day, 5 years ago, when my daughter was diagnosed with vitiligo.
			%br
			%p Vitiligo, seasonal eczema, teen acne...These are skin conditions my beautiful 16-year- old daughter struggles with today. Rosacea, adult acne, and perioral dermatitis…They are all skin conditions I, personally, have been managing for almost 30 years now. As frustrating as it has been to deal with them, they are what have made me an uncompromising chemist and I owe my passion for helping others to them.
			%br
			%p 25 years spent as a biotech/cosmetic chemist, endless hours of formulating and reformulating, my 30-year struggle with problem skin, and the last 7 years spent studying the positive effects of personalized skincare have culminated here in the launching of 3toZEN, where the focus is placed on helping others who live with problem skin manage their conditions and lead happy lives. In getting to this point, there have been a lot of rough moments along the way, but it is serendipity that guides me through it all and, most importantly, to you.
			%br
			%p 3toZEN and I look forward to getting to know you and your skin’s unique needs.
			.headshot
				=image_tag "Sopiea_headshot.jpg"
			%br

app/views/static_pages/checkout.html.haml
.row
  .col-md-12.centered
    %h1.green Checkout

.container
  .jumbotron
    .row
      .col-md-6.offset-md-3.centered
        %h4 OUT OF THE 8 MILLION SKIN CASES WE ANALYZED
        %p 140,000 people have similiar skin as you

    .row.centered
      .col-md-10.offset-md-1{style: 'background: white;'}
        .row
          .col-md-6.cell
            .row
              .col-md-12
                %strong Skin Tone
                %p Tan
          .col-md-6.cell
            .row
              .col-md-12
                %strong Skin Type
                %p Sensitive, Dry
        .row
          .col-md-6.cell
            .row
              .col-md-12
                %strong Stress Level
                %p A little
          .col-md-6.cell
            .row
              .col-md-12
                %strong Concerns
                %p Wrinkles, Aging

.section-2.centered
  .row
    .col-md-6.offset-md-3
      %h1 Pre Launch Special. 50% First Month
      %h1 <strike>$148.00</strike> $79.00



.container-fluid.centered
  .row
    .col-md-4.offset-md-2
      = image_tag "product.jpg", class: "product"
      %p Soothing Concentrate
      %p Begin your personalized regimen with a soothing toner. Contains a blend of Proven Ingredients™ and active Pomegranate Extract, to brighten skin, calming Tasmanian Pepper Extract, and Burdock Root, to clear irritation.
    .col-md-4
      = image_tag "product.jpg", class: "product"
      %p Daily Cleanser
      %p Use our tailor-made serum everyday for glowing, more youthful skin. Infused with naturally hydrating antioxidant, it also contains a concentrated blend of Proven Ingredients™, active Ceramides, to keep skin supple, hydrating Hyaluronic Acid, and Vitamin C. Apply after toning.

  .row
    .col-md-6.offset-md-3
      =link_to "Continue", order_path, class: "btn btn-green"

app/views/static_pages/contact.html.haml
.contact
	.hero
		=image_tag "contact_hero_2.jpg", class: "img-fluid"
%br
.contact
	.row
		.offset-md-3.col-md-6.centered
			%h1 Contact Us
	.row
		.col-md-6.centered
			%p= "Contact email: #{link_to 'sopiea@3toZen.com', 'mailto:sopiea@3toZen.com'}".html_safe 
		.col-md-6.form
			%p.centered Send a message.
			=form_for :messages, url: contact_path do |f|
				=f.label :name
				%br
				=f.text_field :name
				%br
				=f.label :email
				%br
				=f.text_field :email
				%br
				=f.label :subject
				%br
				=f.text_field :subject
				%br
				=f.label :body
				%br
				=f.text_area :body
				%br
				=f.submit "Send"

			- flash.each do |key, value|
				.alert{ :class => "alert-#{key}" }
					%button.close{ :data => { :dismiss => "alert" } } x
					%strong
						= value

app/views/static_pages/faqs.html.haml
=image_tag "faq_hero.jpg", class: "img-fluid"
.faqs
	.row
		.offset-md-3.col-md-6
			%br
			%h1 FAQs
			%p Let's see if we can answer your questions. Here's some commonly asked questions below.
			%br
			%br
		.offset-md-1.col-md-6.questions
			%h2 What is 3toZen?
			%p This is what it do.
			%br
			%h2 Why 3toZen?
			%p This is why.
			%br
			%h2 Cool, where can I buy?
			%p This is where.

app/views/static_pages/home.html.haml
.section-1
  .row
    .tag-line.offset-md-6.col-md-6
      %h2 Personalized Skincare
      %h2 Unique to Your Skin and Lifestyle
      %h2 By Your Very Own Cosmetic Chemist
      = link_to "Get Started", "#", class: "btn btn-primary", data: {toggle: "modal", target: "#skincare-wizard-modal"}

.section-2.centered
  .container
    .row
      .col-md-10.offset-md-1
        %h1 Skincare is most effective, when it is formulated for you.
    %br
    %br
    .row
      .col-md-4
        .fa.fa-user-circle.fa-5x
        %h3 Personalization
        %p Precision skincare. Unique to your needs, lifestyle, and environment.
      .col-md-4
        .fa.fa-android.fa-5x
        %h3 AI
        %p With you as an essential part of our formulative process, we are teaching our algorithms to achieve skincare solutions that will fit you best.
      .col-md-4
        .fa.fa-pagelines.fa-5x
        %h3 Sustainability
        %p Green chemistry that is in sync with our environment, committed to respecting human rights, and protecting cultural heritage.
    %br
    .row
      .col-md-4.offset-md-4
        = link_to "Get Started", "#", class: "btn btn-primary", data: {toggle: "modal", target: "#skincare-wizard-modal"}
    %br

.section-3
  .container-fluid
    .row.centered
      .offset-md-3.col-md-6
        %br
        %h1 Collaborated With
    .row
      .col-md-2.offset-md-1
        .facebook
          =image_tag "fblogo.jpg", class: "img-fluid"
      .col-md-2.offset-md-1
        .quint
          =image_tag "quintessentiallylogo.png", class: "img-fluid"
      .col-md-2.offset-md-1
        .wsj
          =image_tag "wsjdlivelogo.jpg", class: "img-fluid"
      .col-md-2.offset-md-1
        .nokid
          =image_tag "nokidhungry.jpg", class: "img-fluid"
.section-4.centered
  .container-fluid
    .row
      .col-md-12.no-padding
        %h1 Get Started in 3 Steps.
    %br
    .row
      .col-md-3.no-padding
        %h3.heavy.centered 1
        %p Take our online assessment.
      .col-md-9.no-padding
        =image_tag "step1.jpg", class: "img-fluid"
    .row
      .col-md-9.sofia.no-padding
        =image_tag "Sofia_AI.jpg"
      .col-md-3.no-padding
        %h3.heavy.centered 2
        %p Your initial results analyzed by Sofia, our AI.
    .row
      .col-md-3.no-padding
        %h3.heavy.centered 3
        %p Complimentary face-to-face consultation with our cosmetic chemists virtually via FaceTime, Skype, Whatsapp.
      .col-md-9.no-padding
        =image_tag "step3.jpg", class: "img-fluid"
.section-5
  .container-fluid
    .row
      .col-md-12.centered
        %h1 Testimonials
    %br
    .row
      .col-md-4.testimonial-images
        .centered
          =image_tag "Tracy.jpg", class: "img-fluid"
        .row.centered
          .col-md-12
            %h2 Tracy
        .row
          .col-md-8.offset-md-2
            %h3 CA
            %p <i>“I am hooked! My skin tends to be dry and easily irritated…I got compliments all day on how great my skin looked…I have never encountered a product that worked so well!”</i>
      .col-md-4.testimonial-images
        .centered
          =image_tag "George.jpg", class: "img-fluid"
        .row.centered
          .col-md-12
            %h2 George
        .row
          .col-md-8.offset-md-2
            %h3 CA
            %p <i>“There are different formulas for winter vs summer, so it changes with the seasons, and when things get off track we run through the question series again to troubleshoot what’s going on and change up my formulas. It’s simple prevention.”</i>
      %br
      .col-md-4.testimonial-images
        .centered
          =image_tag "Tiffany.jpg", class: "img-fluid"
        .row.centered
          .col-md-12
            %h2 Tiffany
        .row
          .col-md-8.offset-md-2
            %h3 CA
            %p <i>”I have been a client of custom skin care for 3 years and it has truly changed my skin in all the right ways! My lines have softened and my skin is more radiant and even in tone…I appreciate how much research is put into each and every ingredient. I plan to be a client for life!”</i>

.modal.fade#skincare-wizard-modal
  .modal-dialog.modal-lg
    .modal-content
      #skincare-wizard-react{data: ReactProps::SkinCare.props}

= javascript_pack_tag 'skincare-wizard/main'