config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :user_profiles

	resources :messages
  resources :invoices, only: [:new]
  resources :questionnaires, only: [:create]

  resources :charges

  get '/order', to: "invoices#order"

  get "/checkout", to: "static_pages#checkout"

	root "static_pages#home"

	get '/about', to: 'static_pages#about'

	get '/contact', to: 'static_pages#contact'

	get '/faqs', to: 'static_pages#faqs'

	post '/contact', to: 'messages#create'

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  def self.stripe_params_mapping(params)
    {
      "first_name": params["shipping_name"],
      "zipcode": params["shipping_address_zip"],
      "address": params["shipping_address_line1"].titleize,
      "city": params["shipping_address_city"],
      "state": params["shipping_address_state"]
    }
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, optional: true

  before_save :set_answer_number


  def set_answer_number
    self.answer_number = question.answers.count + 1
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing_address.rb
class BillingAddress < Address
  def self.stripe_params_mapping(params)
    {
      "first_name": params["billing_name"],
      "zipcode": params["billing_zip"],
      "address": params["billing_address_line1"],
      "city": params["billing_address_city"].titleize,
      "state": params["billing_address_state"]
    }
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  before_save :set_invoice_number

  private

  def set_invoice_number
    self.invoice_number = "#{Time.now.strftime("%Y%M%S")}-#{user.id}-#{Invoice.count + 1}"
  end
end

app/models/message.rb
class Message < ApplicationRecord
	validates :name, presence: true, length: { minimum: 3, maximum: 30}
	validates :email, presence: true, length: { minimum: 3, maximum: 30}
	validates :subject, presence: true, length: { minimum: 3, maximum: 30}
	validates :body, presence: true, length: { minimum: 3, maximum: 256}
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionnaire, optional: true
  has_many :answers, dependent: :destroy

  default_scope { order(:question_number) }
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :questions
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :invoices
   has_one :questionnaire
   has_one :address
   has_one :billing_address

   def password_required?
    false
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @user = User.find(session[:user_id])
    @invoice = Invoice.find(session[:invoice_id])
  end

  def create
    # Amount in cents
    @amount = render_amount

    customer = Stripe::Customer.create(
      :email => params[:stripe_email],
      :source  => params[:stripe_token]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => '3toZen Purchase',
      :currency    => 'usd'
    )

  save_stripe_info_to_session
  redirect_to new_charge_path

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end



  private
  # need to handle user buying multiple items or have dif shipping address/billing addresses

  def save_stripe_info_to_session
    user = User.new(email: params[:stripe_email])
    invoice = user.invoices.new(total: 5000, status: "paid")
    user.build_address(Address.stripe_params_mapping(stripe_params))
    user.build_billing_address(BillingAddress.stripe_params_mapping(stripe_params))

    q = Questionnaire.find(session[:questionnaire_id])
    q.zipcode = params["shipping_address_zip"]
    user.questionnaire = q
    if user.save
      session[:user_id] = user.id
      session[:invoice_id] = invoice.id
    end

    session[:item] = params[:item]
  end

  def stripe_params
    params.permit!
  end

  def render_amount
    if params[:item] == "oneMonth"
      8630
    else
      16060
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

	def new
		@message = Message.new
	end

	#def show
	#	@message = Message.find(params[:id])
	#end

	def create
		@message = Message.new(message_params)
		if @message.save
			MessagesMailer.send_email(@message).deliver_now!
			flash[:notice] = "Your message has been sent."
			redirect_to contact_path
		else
			flash[:error] = "Sorry, there was an issue sending your message. Try again please."
			redirect_to contact_path
		end
	end

	private
	
		def message_params
			params.require(:messages).permit(:name, :subject, :email, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.haml
%footer
  .row
  %br
    .col-md-12
      = link_to "#" do
        %i.fa.fa-facebook.fa-2x
      = link_to "#" do
        %i.fa.fa-instagram.fa-2x
  %hr{width: "40%"}

  .row
    .col-md-12
      %p Copyright © 3toZen Inc., All rights reserved.
      %p San Francisco, CA

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-md.navbar-light
    %button.navbar-toggler.navbar-toggler-right{type: "button", data: {toggle: "collapse", target: "#navbarNavAltMarkup"}, aria: {controls: "navbarNavAltMarkup", expanded: "false", label: "Toggle navigation"}}
        %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarNavAltMarkup
        .container
            .row
                .col-lg-2
                    = link_to image_tag( "logo.png"), root_path, class: "a navbar-brand.img-fluid"
                .col-lg-2.centered
                    = link_to "Contact Us", contact_path, class: "a nav-item nav-link"
                .col-lg-2.centered
                    = link_to "About", about_path, class: "a nav-item nav-link"
                -#.col-lg-2.centered
                    = link_to "FAQs", faqs_path, class: "a nav-item nav-link"
                
                -# .offset-lg-1.col-lg-1.centered.log-in
                -#     -if !user_signed_in?
                -#         = link_to "Log In", user_session_path
                -# .col-lg-2.log-out.centered
                -#     -if user_signed_in?
                -#         = link_to "Log Out", destroy_user_session_path, :method => :delete

app/views/layouts/application.html.haml
%html
	%head
		%title 3toZen
		= csrf_meta_tags
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-77258470-5"></script>
		%script
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());

			gtag('config', 'UA-77258470-5');

		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


	%body{class: "#{controller_name} #{action_name}"}


		= render "layouts/navbar"

		= yield

		= render "layouts/footer"